FROM gradle:8.10.2-jdk21 AS build
WORKDIR /workspace
COPY . .
ARG PROJECT
RUN gradle :services:${PROJECT}:bootJar --no-daemon

FROM eclipse-temurin:21-jre
WORKDIR /app
ARG PROJECT
COPY --from=build /workspace/services/${PROJECT}/build/libs/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
