/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiFetch } from './fetcher';
export interface CreateOrderItemRequest {
  productId: string;
  sku: string;
  name: string;
  /** @minimum 1 */
  quantity?: number;
  unitPrice: number;
}

export interface CreateOrderRequest {
  customerId?: string;
  paymentCardNumber: string;
  items: CreateOrderItemRequest[];
}

export type CreateOrderResponseStatus = typeof CreateOrderResponseStatus[keyof typeof CreateOrderResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateOrderResponseStatus = {
  CREATED: 'CREATED',
  STOCK_RESERVED: 'STOCK_RESERVED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  READY_FOR_PICKING: 'READY_FOR_PICKING',
  COMPLETED: 'COMPLETED',
  STOCK_RESERVATION_FAILED: 'STOCK_RESERVATION_FAILED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  STOCK_RELEASED: 'STOCK_RELEASED',
  CANCELLED: 'CANCELLED',
} as const;

export interface CreateOrderResponse {
  orderId?: string;
  status?: CreateOrderResponseStatus;
}

export type OrderOverviewDtoStatus = typeof OrderOverviewDtoStatus[keyof typeof OrderOverviewDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderOverviewDtoStatus = {
  CREATED: 'CREATED',
  STOCK_RESERVED: 'STOCK_RESERVED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  READY_FOR_PICKING: 'READY_FOR_PICKING',
  COMPLETED: 'COMPLETED',
  STOCK_RESERVATION_FAILED: 'STOCK_RESERVATION_FAILED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  STOCK_RELEASED: 'STOCK_RELEASED',
  CANCELLED: 'CANCELLED',
} as const;

export interface OrderOverviewDto {
  orderId?: string;
  customerId?: string;
  status?: OrderOverviewDtoStatus;
  totalAmount?: number;
  itemCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export const list = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<OrderOverviewDto[]>(
      {url: `/orders`, method: 'GET', signal
    },
      );
    }
  



export const getListQueryKey = () => {
    return [
    `/orders`
    ] as const;
    }

    
export const getListQueryOptions = <TData = Awaited<ReturnType<typeof list>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({ signal }) => list(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListQueryResult = NonNullable<Awaited<ReturnType<typeof list>>>
export type ListQueryError = unknown


export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const create = (
    createOrderRequest: CreateOrderRequest,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<CreateOrderResponse>(
      {url: `/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrderRequest, signal
    },
      );
    }
  


export const getCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateOrderRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateOrderRequest}, TContext> => {

const mutationKey = ['create'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, {data: CreateOrderRequest}> = (props) => {
          const {data} = props ?? {};

          return  create(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
    export type CreateMutationBody = CreateOrderRequest
    export type CreateMutationError = unknown

    export const useCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateOrderRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create>>,
        TError,
        {data: CreateOrderRequest},
        TContext
      > => {

      const mutationOptions = getCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
